#!/usr/bin/env sh

read -r -d '' POWER << EOM
<box orientation="v" spacing="10" space-evenly="false">
<box space-evenly="false" style="margin: 10px 5px 5px 5px;padding: 0px"
orientation="v" halign="fill" spacing="10">
  <box class="power" orientation="h" halign="center" valign="center" width="50" height="70" style="font-size: 40px;margin: 5px" spacing="10">
    <button onclick="~/.local/bin/eww update hub=false  &amp;&amp; swaylock -f"></button>
    <button onclick="systemctl suspend">鈴</button>
    <button onclick="loginctl terminate-user $USER"></button>
    <button onclick="systemctl poweroff">⏻</button>
  </box>
</box>
EOM

~/.local/bin/eww update content="$POWER"

~/.local/bin/toggle notification
